### ISSUE TITLE
关于你项目UTF-8编码的问题

### ISSUE THREAD

**Issue by rongyouming** [Huangsj1/-c-#1]
1.loadimage的时候你没有对路径参数使用TEXT宏(导致项目只能用多字节字符集编译)
2.你的cpp文件是UTF-8格式的，但是忘记了添加BOM头，导致VS不能识别其中的中文路径
(如果我编译时使用/utf-8选项又没勾选"使用Unicode UTF-8提供全球语言支持"，项目运行时就无法正确读取中文路径)
我这边的解决方法有3种：
1.把你项目里的中文路径全替换成英文的(最简单)
2.把项目属性切换成使用Unicode的，然后一个个在路径前面手动加上TEXT宏或者'L'标记(这样就会使用宽字符版的loadimage)
3.把所有cpp文件手动保存成带BOM头的UTF-8格式
工作量上2>3>1
不能勾选"使用Unicode UTF-8提供全球语言支持"这个选项的原因是我的系统上有一些老的软件，不支持UTF-8编码，开启了界面就会乱码，所以这个选项不是人人都能随便勾选的
综上所述，我最后选择了方案1
最后一个小建议：
也希望你以后开发项目的时候尽量不使用中文路径，也不要把路径写死在代码里，否则一旦你的项目要在别人的环境下编译运行，问题可能会比你想象的多很多。

**Comment by Huangsj1** [comment]
谢谢佬的建议，一定吸取教训（我这个代码是两年前刚学C++做的，所以可能没有考虑这么多，不足之处见谅(*^_^*)）
